package emerson.sample.myPlace.Entities;
import jakarta.persistence.*;
import lombok.*;
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "free_services", indexes = @Index(name = "idx_listing_id", columnList = "listing_id"))
public class FreeServices {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne(
            cascade = CascadeType.REMOVE,
            targetEntity = Listing.class,
            optional = false)
    @JoinColumn(
            name = "listing_id",
            referencedColumnName = "listing_id",
            foreignKey = @ForeignKey(name = "frgKey_freeService_listing"))
    private Listing listing_id;

    @Column(name = "service_name", nullable = false, length = 100)
    private String service_name;

    @Column(name = "description", length = 255)
    private String description;

    // Constructors, Getters and Setters are generated by LOMBOK, pretty cool eh
}

