package com.myplace.usermanagement.entity.EnumClasses;

public enum Interests {
    Programming,
    Reading,
    Hiking,
    Cooking,
    Gaming,
    Traveling,
    Photography,
    Writing,
    Painting,
    Music,
    Dancing,
    Gardening,
    Swimming,
    Cycling,
    Running,
    Fishing,
    Knitting,
    Yoga,
    Meditation,
    Skiing,
    Singing,
    Acting,
    Scuba_Diving,
    Surfing,
    Chess,
    Woodworking,
    DIY_Projects,
    Birdwatching,
    Calligraphy,
    Fashion_Design,
    Pottery,
    Sculpting,
    Rock_Climbing,
    Skydiving,
    Horseback_Riding,
    Archery,
    Billiards,
    Hula_Hooping,
    Magic_Tricks,
    Baking,
    Star_gazing,

    }
